language: java
deploy:
  provider: heroku
  api_key:
    secure: c931a50f-2ba0-4b3b-9f38-1d4e251f414e
  app: sidannar-tictactoe

script: 
 - phantomjs src/Selenium/tests/testSelenium.js
 - ./gradlew check

before_install:
- npm install selenium-webdriver
