language: java

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac"

script:
  - ./gradlew check
  - ./gradlew seleniumXvfb


deploy:
  provider: heroku
  api_key:
    secure: c931a50f-2ba0-4b3b-9f38-1d4e251f414e
  app: sidannar-tictactoe


after_success:
   bash <(curl -s https://codecov.io/bash)