/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import static spark.Spark.*;
import org.json.*;

/** 
 * <h1>Tic Tac Toe</h1>
 * This is the business code of our solution
 * 
 * @since 22-10-2017
*/
public class TicServer {
    String board = "";

    private static int getHerokuPort() {
        ProcessBuilder psb = new ProcessBuilder();
        if (psb.environment().get("PORT") != null) {
            return Integer.parseInt(psb.environment().get("PORT"));
        }
        return 4567;
    }

    private void init(){
        get(
            "/mark/:field", 
            (req, res) -> mark(req.params(":field"))
        );
    }

    private JSONObject mark(String field){
        JSONObject obj = new JSONObject();
        
              obj.put("name", "foo");
              obj.put("num", new Integer(100));
              obj.put("balance", new Double(1000.21));
              obj.put("is_vip", new Boolean(true));

        return obj;
    }

    public static void main(String[] args) {
        staticFileLocation("/public");
        port(getHerokuPort());

        TicServer server = new TicServer();
        server.init();
        
    }
}