
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import static spark.Spark.*;
import org.json.*;

/** 
 * <h1>Tic Tac Toe</h1>
 * This is the business code of our solution
 * 
 * @since 22-10-2017
*/
public class TicServer {
    Tic board;

    private static int getHerokuPort() {
        ProcessBuilder psb = new ProcessBuilder();
        if (psb.environment().get("PORT") != null) {
            return Integer.parseInt(psb.environment().get("PORT"));
        }
        return 4567;
    }

    private void init() {
        board = new Tic();
        get("/mark/:field", (req, res) -> mark(req.params(":field")));
        get("/newGame", (req, res) -> reset());
    }

    private JSONObject mark(String field) {
        int fieldIndex = Integer.parseInt(field);

        try {
            board.updateBoard(fieldIndex);
        } catch (IllegalArgumentException err) {
            return new JSONObject();
        }

        JSONObject obj = new JSONObject();

        char nextPlayer = board.player();

        if (board.isDraw()) {
            obj.put("status", "draw");
        } else if (board.isWinner()) {
            obj.put("status", "win" + nextPlayer);
        } else {
            obj.put("status", "ongoing");
        }

        obj.put("board", board.board());

        obj.put("nextMove", Character.toString(nextPlayer));

        return obj;
    }

    public JSONObject reset(){
        board = new Tic();
        JSONObject obj = new JSONObject();
        obj.put("board", board.board());
        char nextPlayer = board.player();

        if (board.isDraw()) {
            obj.put("status", "draw");
        } else if (board.isWinner()) {
            obj.put("status", "win" + nextPlayer);
        } else {
            obj.put("status", "ongoing");
        }

        obj.put("nextMove", Character.toString(nextPlayer));
        return obj;
    }

    public static void main(String[] args) {
        staticFileLocation("/public");
        port(getHerokuPort());

        TicServer server = new TicServer();
        server.init();

    }
}