/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import static spark.Spark.*;

public class TicTacToe {
    public static String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        get("/", (req, res) -> getGreeting());
    }
}
