/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class TicTacToeTest {
    @Test public void testAppHasAGreeting() {
        TicTacToe classUnderTest = new TicTacToe();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting(1, " "));
    }
}
